[Unit]
Requires=gateway-vpn-vps-firewall.service
After=gateway-vpn-vps-firewall.service
ConditionPathExists=|!/var/lib/gateway-vpn-vps/install-transactions/active
ConditionPathExists=|/run/gateway-vpn-vps-install-authorized
ConditionPathIsSymbolicLink=!/var/lib/gateway-vpn-vps/install-transactions/active
ConditionPathIsSymbolicLink=!/run/gateway-vpn-vps-install-authorized
